name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.3'
        otp-version: '24.3'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install Nerves requirements
      run: sudo apt install build-essential automake autoconf git squashfs-tools ssh-askpass pkg-config curl
    - name: Update hex and rebar
      run: mix local.hex --force && mix local.rebar --force
    - name: Install dependencies
      run: mix archive.install hex nerves_bootstrap --force && mix deps.get
    - name: Compile Code
      run:  mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
